### ISSUE TITLE
To Do -- Final LandWeb app

### ISSUE THREAD

**Issue by eliotmcintire** [PredictiveEcology/LandWeb#23]
- [x] Duplicate Gov Alberta icon (with #28; done in c345687)
- [x] <s>Authors of SpaDES.shiny not correctly rendered (SpaDES is correct)</s> (with #28; see [comment](https://github.com/eliotmcintire/LandWeb/issues/23#issuecomment-385426832) below)
- [x] Rmd files for all modules -- update so it is correct
- [x] Write: AgeClass = 0, 40, 80, 120 stated somewhere (Young, Immature, Mature, Old) ... these are 2 global variables `ageClasses` and `ageClassCutoffs` (approximate names, sorry)
- [x] remove `AB Natural Sub Regions` and `LandWeb Study Area` from list of selectable polygons (they don't work for some reason)
- [x] App Info Pages

    - [x] Overview tab or page describing what this app is, how to interpret it
    - [x] authors, funding, partner info
    - [x] dummy ToS and Privacy pages
    - [x] help page (support contact info and FAQ)

- [x] App Privacy Policy (6bf81c381297b21af6c038ace93fac3e16daa7aa) & Terms of Service (b062293ca5700ed76e7faef872a2e8e188b92c68) (with #37)
- [x] Update main README file with app/data info etc. -- this is included in user's download (with #26)
- [x] Run FULL LandWeb app (`LandWeb_parameters.R`)

    - [x] Test with various options in app

- [x] backup `/mnt/shared/LandWeb/` on 342:

    ```bash
    rsync -avP --delete /mnt/shared/LandWeb/ /mnt/data/LandWeb-backup/
    ```

- [x] Push to landweb.ca 

    - [x] install R and required system dependencies for packages
    - [x] install rstudio-server
    - [x] install shiny-server
    - [x] clone LandWeb repo
    - [x] rsync the `cache/`, `outputs/`, and `www/` folders (*after* paring down the cache per below):

        - the cache is HUGE -- it is not all needed to run
        - Run whole app once through, noting the time that you started
        - For safety, make a backup (entire copy of Cache), if drive has enough space [it doesn't, but make backup on 342]
        - `showCache(after = appStartTime)` # confirm looks good
        - `keepCache(after = appStartTime)` # delete everything but the stuff that was touched since the app started.
    - [x] setup Google oauth stuff with fRI's Google API account
    - [x] update Google oauth info in app to use fRI's Google API account
    - [x] <s>add fRI.LandWeb@gmail.com as owner of data folder in Google Drive</s>
    - [x] <s>authorize LandWeb users via Google Drive sharing</s>
    - [x] add google analytics for landweb.ca
    - [x] update model/tech support info to Alex (after June 4)

- [x] Offload app to landweb.ca and fRI Research
- [x] final clean up of code

    - [ ] remove all (if possible) hard codings
    - [x] merge `reactive-sims` branch back into `development`
    - [x] delete old/stale branches (`RIA` and `reactive-sims`) (#34)
    - [ ] other ...

- [x] merge `development` into `master` and create new tag `v1.0.0` for deployment
