### ISSUE TITLE
To Do

### ISSUE THREAD

**Issue by eliotmcintire** [PredictiveEcology/LandWeb#3]
- [x] Get LandMine spread closer to Andison & realistic for large fires
- [x] Use Paul Pickell, CASFRI 
- [x] Use new "Current Condition" for input data layers
- [x] Get current condition calculated for all variables
- [x] Use new and old StudyArea & FireReturnArea maps -- selectable by user
- [x] Shiny - map out structure of SpaDES.shiny
- [x] Shiny - clean up:

    - [x] Polygons not labelled correctly (need clean data with meaningful names; add ability to use colname from spdf for labels)
    - [x] Frequency distributions - identical axes
    - [x] Current condition as dot or arrow, include quartiles (wait until we have all the current conditions)
    - [x] Allow exporting of each graph, table, or raw data that built a graph and also "the whole lot" for a given polygon
    - [x] shiny modules should be more generic:

        - [x] `TimeSinceFire` --> `timeSeriesofRasters`;
        - [x] generalize code within `timeSeriesofRasters` (https://github.com/PredictiveEcology/SpaDES.shiny/issues/96);
        - [x] generalize code within `clumpMod2` (https://github.com/PredictiveEcology/SpaDES.shiny/issues/97);
        - [x] (generalize code within `largePatches`); rename to `patchSize` or similar; (with https://github.com/PredictiveEcology/SpaDES.shiny/issues/97)

    - [x] Filenames of say, tsf and vtm, should be derived from the outputs(sim), rather than manually
    - [x] Loop over all maps for gdal2Tiles and other histogram generation *before* user required to do it
    - [x] Keep data secure, and inform partners of security situation (see #16)

- [x] Workshop -- announce known ones and discuss possible visit to fRI Research groups
